language: go
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

gobuild_args: -a -installsuffix cgo -ldflags "-X main.Version master"

before_install:
  - pwd
  - mysql -e 'CREATE DATABASE test;'
  - cp $GOPATH/src/github.com/snowlyg/IrisAdminApi/application.example.yml $GOPATH/src/github.com/snowlyg/IrisAdminApi/application.yml
install: true
sudo: required

services:
  - redis
  - mysql

go:
  - 1.15.x
os:
  - linux

env:
  global:
    - GOARCH=amd64
    - GOARCH=386
    - GO111MODULE=on
    - GOPROXY=https://goproxy.cn,direct

script:
  - go vet ./...
  - go test ./... -v -tags test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
