language: go

install:
  -
  - go env -w GO111MODULE=on
  - go env -w GOPROXY=https://goproxy.cn,direct
  - cd backend && go get -d -t -v -u ./... && go build -v ./...

go:
  - 1.14.x

os:
  - windows
  - linux
  - osx

env:
  matrix:
    - GOARCH=amd64
    - GOARCH=386

script:
  - cp /config/application.yml.example backend/application/conf.yml
  - touch ./tmp/tgorm.db
  - cd backend &&  go vet ./...
  - cd backend && go test ./... -v -coverprofile=coverage.txt -covermode=atomic
after_success:
  - bash <(curl -s https://codecov.io/bash)