language: go

gobuild_args: -x -ldflags "-X main.VersionString v1.2.3"
before_install:
  - cd ./server

install:
  - go get -d -t -v -u ./... && go build

go:
  - 1.14.x

os:
  - windows
  - linux
  - osx


env:
  matrix:
    - GOARCH=amd64
    - GOARCH=386
    - GO111MODULE=on
    - GOPROXY=https://goproxy.cn,direct

after_success:
  - bash <(curl -s https://codecov.io/bash)