language: go
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

gobuild_args: -a -installsuffix cgo -ldflags "-X main.Version master"

before_install:
  - cd www && sudo apt-get -y install nodejs
  - npm i
  - npm run build:stage
  - go get -u github.com/go-bindata/go-bindata/v3/go-bindata
  - go generate

install: true
sudo: required

go:
  - 1.14.x

os:
  - windows
  - linux
  - osx

env:
  global:
    - GOARCH=amd64
    - GOARCH=386
    - GO111MODULE=on
    - GOPROXY=https://goproxy.cn,direct

script:
  - go vet ./...
  - go test ./... -v -tags test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)