language: go

install:
  - go env -w GO111MODULE=on
  - go env -w GOPROXY=https://goproxy.cn,direct
  - go get -d -t -v -u ./... && go build

go:
  - 1.14.x

os:
  - windows
  - linux
  - osx

gobuild_args: -x -ldflags "-X main.VersionString v1.2.3"

env:
  matrix:
    - GOARCH=amd64
    - GOARCH=386

after_success:
  - bash <(curl -s https://codecov.io/bash)