language: go

go:
  - 1.18.x

before_script:
  - sudo redis-server /etc/redis/redis.conf --port 6379 --requirepass 'secret'
  - mkdir -p data/db
  - mongod --dbpath=data/db &
  - sleep 5
  - mongo test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'

services:
  - mysql

env:
  - GO111MODULE=on redisPwd=secret mongoAddr=travis:test@127.0.0.1:27017

before_install:
  - go get -v -t ./...

script:
  - go test  -v -race -coverprofile='coverage.txt' -covermode=atomic github.com/snowlyg/iris-admin/g github.com/snowlyg/iris-admin/migration github.com/snowlyg/iris-admin/seed github.com/snowlyg/iris-admin/server/...

after_success:
  - bash <(curl -s https://codecov.io/bash)
