loglevel: info # 日志级别 info debug 等等
bindata: false # 不前后端分离 true,false
debug: false # 调试模式
https: false # https
host: 127.0.0.1 # host 地址
port: 8086 # 端口
db:
  adapter: sqlite3 # mysql postgres sqlite3
redis:
  host: localhost
  port: 6379
  pwd: foobared
