captcha:
  img-height: 80
  img-width: 240
  key-long: 6
mysql:
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: ""
  log-mode: false
  log-zap: ""
  max-idle-conns: 0
  max-open-conns: 0
  password: ""
  path: ""
  username: ""
redis:
  addr: ""
  db: 0
  password: ""
  pool-size: 0
system:
  addr: ""
  level: debug
zap:
  director: log
  encode-level: LowercaseColorLevelEncoder
  format: console
  level: info
  link-name: latest_log
  log-in-console: true
  prefix: '[OP-ONLINE]'
  showline: false
  stacktrace-key: stacktrace
