version: '2'
services:
  mysql:
    user: "1000:50"
    image: mysql:8.0.13
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./mysql/data:/var/lib/mysql/:rw
    restart: always
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
      TZ: "Asia/Shanghai"
  irisadminapi:
    build:
      context: backend
      dockerfile: Dockerfile
    container_name: irisadminapi
    ports:
      - "5000:5000"
    restart: always
    networks:
      - default
    links:
      - "mysql:mysql"
networks:
  default: